# Generated by Django 5.2 on 2025-04-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manicuristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('motivo', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista')),
            ],
        ),
    ]
