# Generated by Django 5.2 on 2025-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=45)),
                ('num_documento', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
    ]
