# Generated by Django 5.2 on 2025-04-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('manicuristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoHasAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimientos.abastecimiento')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
            ],
        ),
    ]
